version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"  # Exponer el puerto 5003
    container_name: zeli_page
    restart: always

    volumes:
      - ./page:/var/www/html/page
    environment:
      - VIRTUAL_HOST=zeli.com.ar
