version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5040:80"  # Exponer el puerto 5040
    container_name: bodega_tronelli
    restart: always

    volumes:
      - ./page:/var/www/html/page
    environment:
      - VIRTUAL_HOST=bodegatronelli.com.ar
